/* Nonblocking action feedback; never moves focus or interrupts clipboard activation. */
(function(root){
let timer,pending=null;const box=document.getElementById('action-popup'),message=document.getElementById('action-popup-message');
function show(text,kind='info'){clearTimeout(timer);message.textContent=text;box.dataset.kind=kind;box.hidden=false;if(kind!=='progress')timer=setTimeout(()=>box.hidden=true,12000);}
document.getElementById('action-popup-close').addEventListener('click',()=>{clearTimeout(timer);box.hidden=true;});
const copyMessages={'copy-rules':'복사되었습니다.','copy-prompt':'프롬프트가 복사되었습니다. 이제 AI에게 이 프롬프트를 붙여넣으세요.','copy-blog':'블로그 내용이 복사되었습니다. 이제 네이버 블로그 편집창에 붙여 넣으세요.'};
function downloaded(){pending=null;show(MobileClipboard.isIOS()?'아이폰에서는 저장 또는 공유 버튼을 눌러 저장 위치를 지정해 주세요. 공유 메뉴에서 파일에 저장을 선택할 수 있습니다.':'다운로드를 시작했습니다. 기본 설정에서는 다운로드 폴더에 저장됩니다. 파일을 확인해 주세요.','success');}
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||button.disabled||button.id==='action-popup-close')return;const id=button.id;let scope=['status'];if(id.startsWith('copy-'))scope=[id==='copy-blog'?'blog-status':'status'];else if(id.startsWith('manual-'))scope=['manual-copy-status'];else if(id.startsWith('draft-')||button.closest('#draft-history'))scope=['draft-status'];else if(id==='share-file')scope=['save-file-status'];else if(id==='gps-search')scope=['gps-search-status'];else if(button.closest('#gps-favorites')||button.closest('#gps-search-results')){show('좌표를 적용했습니다. 이미지를 선택하면 자동으로 처리됩니다.','success');pending=null;return;}else if(id.startsWith('download-gps'))scope=['gps-status'];else if(button.closest('#library-list'))scope=['library-status'];pending={id,scope,at:Date.now()};show((button.textContent||'작업').trim()+' 작업을 진행하고 있습니다. 잠시 기다려 주세요.','progress');},true);
const observed=['status','blog-status','manual-copy-status','library-status','gps-status','gps-search-status','draft-status','save-file-status'];const observer=new MutationObserver(records=>{if(!pending||Date.now()-pending.at>90000)return;for(const record of records){const node=record.target.nodeType===3?record.target.parentElement:record.target;const area=node.closest?.('[id]');if(!area||!pending.scope.includes(area.id))continue;const text=area.textContent.trim();if(!text||/자동 저장 완료|자동 저장 중|미리보기 준비/.test(text)&&pending.id!=='draft-save')continue;if(/복사 완료/.test(text)&&copyMessages[pending.id]){show(copyMessages[pending.id],'success');pending=null;return;}if(/실패|불가|제한|올바르|초과|확인해|차단/.test(text)){show(text,'error');pending=null;return;}let next=text;if(/저장 완료/.test(text))next+=' 저장한 내용을 계속 사용하거나 히스토리에서 불러올 수 있습니다.';if(/삭제했습니다/.test(text))next+=' 필요한 이미지를 다시 추가해 주세요.';if(/JSON 입력값을 불러/.test(text))next+=' 복원된 입력을 확인하고 계속 작업하세요.';if(/리셋했습니다/.test(text))next+=' 새 내용을 입력하거나 히스토리에서 이전 값을 불러오세요.';const progressing=/중|대기|준비/.test(text);show(next,progressing?'progress':'success');if(!progressing)pending=null;}});
for(const id of observed){const node=document.getElementById(id);if(node)observer.observe(node,{subtree:true,childList:true,characterData:true});}
document.addEventListener('change',event=>{if(event.target.id==='library-upload'){pending={id:'library-upload',scope:['library-status'],at:Date.now()};show('이미지를 저장하고 있습니다. 완료 후 삽입 위치를 선택해 주세요.','progress');}else if(event.target.id==='gps-file'){pending={id:'gps-file',scope:['gps-status'],at:Date.now()};show('이미지를 순서대로 처리하고 있습니다. 완료되면 다운로드 버튼을 눌러 주세요.','progress');}else if(event.target.id==='draft-import'){pending={id:'draft-import',scope:['draft-status'],at:Date.now()};show('JSON 파일을 확인하고 입력값을 불러오고 있습니다.','progress');}},true);
root.ActionPopup={show,downloaded};
})(globalThis);