/* Autosaved text drafts and bounded device-local history. Image files stay in the library. */
(async function(){
'use strict';
const key='blog-prompt-helper-drafts-v1',ids=['original','blog-code','blog-contact-phone','blog-contact-position','gps-mode','gps-address','gps-name','gps-lat','gps-lon'];
const status=document.getElementById('draft-status'),list=document.getElementById('draft-history');
const historyLifetime=24*60*60*1000;
let state={current:null,history:[]},timer,historyTimer,ready=false,lastCheckpoint;
await libraryReady;
try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(raw&&Array.isArray(raw.history)){state={current:raw.current,history:raw.history.slice(0,50)};}}catch{status.textContent='저장된 기록을 읽지 못했습니다. 새 입력부터 다시 저장합니다.';}
function snapshot(){return {fields:Object.fromEntries(ids.map(id=>[id,document.getElementById(id).value])),images:savedImageItems.map(item=>({id:item.id,label:item.label,phone:item.phone,position:item.position}))};}
function same(a,b){return JSON.stringify(a)===JSON.stringify(b);}
function prune(){const now=Date.now(),before=state.history.length;state.history=state.history.filter(entry=>Number.isFinite(entry.at)&&now-entry.at<historyLifetime&&entry.at<=now);return before!==state.history.length;}
function write(){prune();try{localStorage.setItem(key,JSON.stringify(state));status.textContent='자동 저장 완료 · '+new Date().toLocaleTimeString('ko-KR');return true;}catch(error){while(state.history.length>1){state.history.pop();try{localStorage.setItem(key,JSON.stringify(state));status.textContent='저장 공간에 맞춰 오래된 기록을 정리했습니다.';render();return true;}catch{}}status.textContent='자동 저장 실패: 브라우저 저장 공간이나 사이트 저장 권한을 확인해 주세요.';return false;}}
function save(){clearTimeout(timer);state.current={at:Date.now(),data:snapshot()};write();}
function checkpoint(label='자동 저장',force=false){clearTimeout(historyTimer);const data=snapshot();if(!force&&same(lastCheckpoint,data))return;lastCheckpoint=data;state.history.unshift({id:crypto.randomUUID(),at:Date.now(),label,data});state.history=state.history.slice(0,50);state.current={at:Date.now(),data};write();render();}
async function apply(data){if(!data||!data.fields)return;for(const id of ids){if(typeof data.fields[id]==='string')document.getElementById(id).value=data.fields[id];}for(const record of data.images||[]){const item=savedImageItems.find(i=>i.id===record.id);if(!item)continue;for(const field of ['label','phone','position'])if(typeof record[field]==='string')item[field]=record[field];try{await SavedImageLibrary.update(item.id,{label:item.label,phone:item.phone,position:item.position});}catch{libraryStatus.textContent='이미지 설정 저장에 실패했습니다.';}}
renderLibrary();update();updateBlog();document.getElementById('gps-coordinates').hidden=gpsMode.value!=='set';gpsAutoName='';searchVersion++;document.getElementById('gps-location').hidden=true;document.getElementById('gps-search-results').replaceChildren();document.querySelectorAll('#gps-favorites button').forEach(b=>b.setAttribute('aria-pressed','false'));scheduleBatch(0);try{await SavedImageLibrary.setting('contact',{phone:contactPhone.value,position:contactPosition.value});}catch{} }
function render(){prune();list.replaceChildren();if(!state.history.length){const p=document.createElement('p');p.className='note';p.textContent='입력하면 히스토리가 자동으로 만들어집니다.';list.append(p);return;}for(const entry of state.history){const row=document.createElement('div');row.className='file-result';const p=document.createElement('p');const fields=entry.data?.fields||{};p.textContent=new Date(entry.at).toLocaleString('ko-KR')+' · '+entry.label+' · '+(fields.original||fields['blog-code']||fields['gps-name']||fields['blog-contact-phone']||'빈 입력').replace(/\s+/g,' ').slice(0,70);const b=document.createElement('button');b.type='button';b.textContent='불러오기';b.addEventListener('click',async()=>{if(Date.now()-entry.at>=historyLifetime){prune();write();render();status.textContent='이 기록은 생성 후 24시간이 지나 만료되었습니다.';return;}b.disabled=true;checkpoint('불러오기 전');await apply(entry.data);save();status.textContent='이전 입력을 불러와 저장했습니다.';b.disabled=false;});row.append(p,b);list.append(row);}}
lastCheckpoint=state.history[0]?.data||state.current?.data;if(prune())write();
if(state.current?.data){await apply(state.current.data);status.textContent='마지막 자동 저장 입력을 복원했습니다.';}render();ready=true;
function changed(){if(!ready)return;save();clearTimeout(historyTimer);historyTimer=setTimeout(()=>checkpoint(),2000);}
document.addEventListener('input',event=>{if(ids.includes(event.target.id)||event.target.closest('#library-list'))changed();});document.addEventListener('change',event=>{if(ids.includes(event.target.id)||event.target.closest('#library-list'))changed();});document.getElementById('gps-favorites').addEventListener('click',changed);document.getElementById('gps-search-results').addEventListener('click',changed);
setInterval(()=>{if(ready&&prune()){write();render();}},1000);
setInterval(()=>{if(ready&&state.current&&!same(lastCheckpoint,snapshot()))checkpoint();},30000);
window.addEventListener('pagehide',()=>{if(ready){save();checkpoint('페이지 종료 전');}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&ready){save();checkpoint();}});
document.getElementById('draft-save').addEventListener('click',()=>{save();checkpoint('직접 저장',true);});
document.getElementById('draft-reset').addEventListener('click',async()=>{checkpoint('리셋 전');clearTimeout(timer);clearTimeout(historyTimer);const fields=Object.fromEntries(ids.map(id=>[id,'']));fields['gps-mode']='remove';fields['blog-contact-position']='end';gpsFiles=[];gpsFile.value='';await apply({fields,images:savedImageItems.map(item=>({id:item.id,label:item.label,phone:item.phone,position:'none'}))});save();status.textContent='입력값을 리셋했습니다. 이전 값은 히스토리에서 불러올 수 있습니다.';});
function validateImport(value){
 if(!value||value.format!=='blog-prompt-helper-inputs'||value.version!==1||!value.data||typeof value.data.fields!=='object'||Array.isArray(value.data.fields))throw new Error('이 도구에서 저장한 입력 JSON 파일을 선택해 주세요.');
 const fields={};for(const id of ids){const text=value.data.fields[id];if(typeof text!=='string')throw new Error('입력 항목이 누락되었거나 형식이 잘못되었습니다: '+id);const element=document.getElementById(id);if(element.tagName==='SELECT'&&!Array.from(element.options).some(option=>option.value===text))throw new Error('선택값이 올바르지 않습니다: '+id);if(element.maxLength>0&&text.length>element.maxLength)throw new Error('입력 길이를 초과했습니다: '+id);if((id==='gps-lat'||id==='gps-lon')&&text!==''&&(!Number.isFinite(Number(text))||Math.abs(Number(text))>(id==='gps-lat'?90:180)))throw new Error('GPS 좌표가 올바르지 않습니다.');fields[id]=text;}
 if(!Array.isArray(value.data.images)||value.data.images.length>1000)throw new Error('이미지 설정 형식이 잘못되었습니다.');
 const images=value.data.images.map(record=>{if(!record||typeof record.id!=='string'||typeof record.label!=='string'||record.label.length>80||typeof record.phone!=='string'||record.phone.length>40||!['none','start','end','both'].includes(record.position))throw new Error('이미지 설정이 올바르지 않습니다.');return {id:record.id,label:record.label,phone:record.phone,position:record.position};});return {fields,images};
}
document.getElementById('draft-export').addEventListener('click',()=>{save();const output={format:'blog-prompt-helper-inputs',version:1,exportedAt:new Date().toISOString(),data:snapshot()};downloadBlob(new Blob([JSON.stringify(output,null,2)],{type:'application/json;charset=utf-8'}),'블로그입력_'+new Date().toISOString().replace(/[:.]/g,'-')+'.json');status.textContent='현재 입력값을 JSON 파일로 다운로드했습니다.';});
document.getElementById('draft-import').addEventListener('change',async event=>{const input=event.target,file=input.files[0];if(!file)return;input.disabled=true;try{if(file.size>10*1024*1024)throw new Error('JSON 파일은 10MB 이하로 선택해 주세요.');const data=validateImport(JSON.parse(await file.text()));checkpoint('JSON 불러오기 전');clearTimeout(timer);clearTimeout(historyTimer);await apply(data);save();checkpoint('JSON 불러오기',true);status.textContent='JSON 입력값을 불러와 자동 저장했습니다.';}catch(error){status.textContent='JSON 불러오기 실패: '+(error instanceof SyntaxError?'올바른 JSON 파일이 아닙니다.':error.message);}finally{input.disabled=false;input.value='';}});
})();