/* Autosaved text drafts and bounded device-local history. Image files stay in the library. */
(async function(){
'use strict';
const key='blog-prompt-helper-drafts-v1',ids=['original','blog-code','blog-contact-phone','blog-contact-position','gps-mode','gps-address','gps-name','gps-lat','gps-lon'];
const status=document.getElementById('draft-status'),list=document.getElementById('draft-history');
let state={current:null,history:[]},timer,historyTimer,ready=false;
await libraryReady;
try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(raw&&Array.isArray(raw.history)){state={current:raw.current,history:raw.history.slice(0,50)};}}catch{status.textContent='저장된 기록을 읽지 못했습니다. 새 입력부터 다시 저장합니다.';}
function snapshot(){return {fields:Object.fromEntries(ids.map(id=>[id,document.getElementById(id).value])),images:savedImageItems.map(item=>({id:item.id,label:item.label,phone:item.phone,position:item.position}))};}
function same(a,b){return JSON.stringify(a)===JSON.stringify(b);}
function write(){try{localStorage.setItem(key,JSON.stringify(state));status.textContent='자동 저장 완료 · '+new Date().toLocaleTimeString('ko-KR');return true;}catch(error){while(state.history.length>1){state.history.pop();try{localStorage.setItem(key,JSON.stringify(state));status.textContent='저장 공간에 맞춰 오래된 기록을 정리했습니다.';render();return true;}catch{}}status.textContent='자동 저장 실패: 브라우저 저장 공간이나 사이트 저장 권한을 확인해 주세요.';return false;}}
function save(){clearTimeout(timer);state.current={at:Date.now(),data:snapshot()};write();}
function checkpoint(label='자동 저장'){clearTimeout(historyTimer);const data=snapshot();if(state.history[0]&&same(state.history[0].data,data))return;state.history.unshift({id:crypto.randomUUID(),at:Date.now(),label,data});state.history=state.history.slice(0,50);state.current={at:Date.now(),data};write();render();}
async function apply(data){if(!data||!data.fields)return;for(const id of ids){if(typeof data.fields[id]==='string')document.getElementById(id).value=data.fields[id];}for(const record of data.images||[]){const item=savedImageItems.find(i=>i.id===record.id);if(!item)continue;for(const field of ['label','phone','position'])if(typeof record[field]==='string')item[field]=record[field];try{await SavedImageLibrary.update(item.id,{label:item.label,phone:item.phone,position:item.position});}catch{libraryStatus.textContent='이미지 설정 저장에 실패했습니다.';}}
renderLibrary();update();updateBlog();document.getElementById('gps-coordinates').hidden=gpsMode.value!=='set';gpsAutoName='';searchVersion++;document.getElementById('gps-location').hidden=true;document.getElementById('gps-search-results').replaceChildren();document.querySelectorAll('#gps-favorites button').forEach(b=>b.setAttribute('aria-pressed','false'));scheduleBatch(0);try{await SavedImageLibrary.setting('contact',{phone:contactPhone.value,position:contactPosition.value});}catch{} }
function render(){list.replaceChildren();if(!state.history.length){const p=document.createElement('p');p.className='note';p.textContent='입력하면 히스토리가 자동으로 만들어집니다.';list.append(p);return;}for(const entry of state.history){const row=document.createElement('div');row.className='file-result';const p=document.createElement('p');const fields=entry.data?.fields||{};p.textContent=new Date(entry.at).toLocaleString('ko-KR')+' · '+entry.label+' · '+(fields.original||fields['blog-code']||fields['gps-name']||fields['blog-contact-phone']||'빈 입력').replace(/\s+/g,' ').slice(0,70);const b=document.createElement('button');b.type='button';b.textContent='불러오기';b.addEventListener('click',async()=>{b.disabled=true;checkpoint('불러오기 전');await apply(entry.data);save();status.textContent='이전 입력을 불러와 저장했습니다.';b.disabled=false;});row.append(p,b);list.append(row);}}
if(state.current?.data){await apply(state.current.data);status.textContent='마지막 자동 저장 입력을 복원했습니다.';}render();ready=true;
function changed(){if(!ready)return;status.textContent='자동 저장 중…';clearTimeout(timer);timer=setTimeout(save,300);clearTimeout(historyTimer);historyTimer=setTimeout(()=>checkpoint(),2000);}
document.addEventListener('input',event=>{if(ids.includes(event.target.id)||event.target.closest('#library-list'))changed();});document.addEventListener('change',event=>{if(ids.includes(event.target.id)||event.target.closest('#library-list'))changed();});document.getElementById('gps-favorites').addEventListener('click',changed);document.getElementById('gps-search-results').addEventListener('click',changed);
setInterval(()=>{if(ready&&state.current&&!same(state.history[0]?.data,snapshot()))checkpoint();},30000);
window.addEventListener('pagehide',()=>{if(ready){save();checkpoint('페이지 종료 전');}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&ready){save();checkpoint();}});
document.getElementById('draft-save').addEventListener('click',()=>{save();checkpoint('직접 저장');});
document.getElementById('draft-reset').addEventListener('click',async()=>{checkpoint('리셋 전');clearTimeout(timer);clearTimeout(historyTimer);const fields=Object.fromEntries(ids.map(id=>[id,'']));fields['gps-mode']='remove';fields['blog-contact-position']='end';gpsFiles=[];gpsFile.value='';await apply({fields,images:savedImageItems.map(item=>({id:item.id,label:item.label,phone:item.phone,position:'none'}))});save();status.textContent='입력값을 리셋했습니다. 이전 값은 히스토리에서 불러올 수 있습니다.';});
})();